services:
  familienberatung:
    container_name: familienberatung
    image: familienberatung:latest
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    volumes:
      - ./data:/data

    environment:
      - TZ=Europe/Berlin
      - SPRING_PROFILES_ACTIVE=prod

    restart: unless-stopped