vaadin.launch-browser=true
spring.application.name=FamilienBeratung
spring.web.locale=de_DE
spring.web.locale-resolver=fixed
spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.datasource.url=jdbc:sqlite:./data/app.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.orm.jdbc.bind=off

storage.base-path=${STORAGE_BASE_PATH:/app/storage}